[package]
name = "connect"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
#opt-level = "z"     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.

[profile.bloat]
inherits = "release"
strip = false

[dependencies]
shared = { git = "https://github.com/samply/beam", branch="develop" }

#axum = "0.5.12"
tokio = { version = "1", features = ["macros","rt-multi-thread","signal"] }
hyper = { version = "0", features = ["full"] }
tower-http = { version = "0", features = ["trace"] }
tower = "*"

# HTTP client with proxy support
hyper-tls = "0.5.0"
hyper-proxy = "0.9.1"
mz-http-proxy = { version = "0.1.0", features = ["hyper"] }

log = "*"
pretty_env_logger = "*"

serde = "*"
serde_json = "*"
hyper_serde = "0.13"

clap = {version = "4", features = ["derive"]}

thiserror = "*"
http-serde = "1.1.2"
http = "0.2.8"

[build-dependencies]
build-data = "0"
