name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Fetch new base image updates every night at 1am
    - cron: '0 1 * * *'

env:
  CARGO_TERM_COLOR: always
  PROFILE: release

jobs:
  build-with-samply:
    uses: samply/github-workflows/.github/workflows/rust.yml@main
    with:
      # For information on these variables, please refer to https://github.com/samply/github-workflows/tree/main/.github/workflows/rust.yml
      # Docker Hub name will be {image-prefix}{component}
      image-prefix: "samply/"
      components: '[ "beam-connect" ]'
      #architectures: '[ "amd64" ]'
      #profile: debug
      test-via-script: true
      features: '[ "", "sockets" ]'
      push-to: ${{ (github.ref_protected == true || github.event_name == 'workflow_dispatch') && 'dockerhub' || 'none' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}